# Register at https://openweathermap.org to get your API key
api_key = "6295bee7484117a8d9c7d8bc2ffc5664"

# This is for Montreal, find your city at https://openweathermap.org
# The id will be the last part of the URL
city_id = "5666639"

# Display settings
units = "imperial"
display_symbol = "°F"
